# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  only:
    - master
    - develop
  except:
    - gh-pages

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - .github/*
    - docs/*

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  choco install gitversion.portable -pre -y


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                               # enable MSBuild parallel builds
  project: src/ContasEmDia.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - nuget restore src/ContasEmDia.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

#---------------------------------#
#       tests configuration       #
#---------------------------------#



#---------------------------------#
#      artifacts configuration    #
#---------------------------------#



#---------------------------------#
#     deployment configuration    #
#---------------------------------#



#---------------------------------#
#        global handlers          #
#---------------------------------#



#---------------------------------#
#         notifications           #
#---------------------------------#
